protected/controllers/ConfController.php
<?php

class ConfController extends Controller
{
    public $layout='//layouts/column1';

    public function accessRules()
    {
        return array(
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','addsetting','updatesetting'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }


    public function actionIndex($c)
	{
        $confFile=AsteriskConfigs::createConfigParser($c);
        $confs=$confFile->parseFileContent();

        $content=array();
        foreach($confs as $key=>$value){
            if (count($value)==0){
                $confLine=array('section'=>$key,'key'=>'','value'=>'');
                array_push($content,$confLine);
            }else{
                for($i=0;$i<count($value);$i++){
                    $equal_sign=EqualSignConf::getSign($value[$i]['equal_sign']);
                    foreach ($value[$i] as $keyLine=>$valueLine) {
                        if ($keyLine!='equal_sign'){
                            $confLine=array('section'=>$key,'key'=>$keyLine,'value'=>$valueLine,'pos'=>$i,'equal_sign'=>$equal_sign);
                            array_push($content,$confLine);
                        }
                    }
                }
            }
        }

        //print_r($content);

        $this->setPageTitle($confFile->getFileName());

		$this->render('index',
            array(
                'content'=>$content,
                'conf'=>$c,
                'fileName'=>$confFile->getFileName()
            )
        );
	}

    public function actionAddSetting($section,$key,$equal,$value,$pos)
    {
        /*$dahdiFile=new AsteriskChanDahdiFile();
        $dahdiFile->addSetting($section,$key,$equal,$value,$pos);*/
    }

    public function  actionUpdateSetting($section,$key,$equal,$value,$pos)
    {
        /*$dahdiFile=new AsteriskChanDahdiFile();
        $dahdiFile->updateSetting($section,$key,$equal,$value,$pos);*/
    }


}

protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    public $layout='//layouts/column1';
    private $asterisk='asterisk';
    private $initScript='/etc/init.d/asterisk';

    public function accessRules()
    {
        return array(
            array('allow',  // allow all users to perform 'index' and 'view' actions
                'actions'=>array('index','login'),
                'users'=>array('*'),
            ),
            array('allow', // allow admin user to perform 'admin' and 'delete' actions
                'actions'=>array('index','login','logout','getServerState','getAsteriskState','error','dialplanReload','IniFile','cdr'),
                'users'=>array('admin'),
            ),
            array('deny',  // deny all users
                'users'=>array('*'),
            ),
        );
    }

	public function actions()
	{
		return array(
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

    private function isAstriskExists()
    {
        $output = exec('echo $PATH;2>&1',$op,$ret_val);
        $paths=explode(':',$output);

        foreach($paths as $path){
            if (file_exists($path.'/asterisk'))
                return true;
        }

        return false;
    }

    private function getAsteriskPath()
    {
        $output = exec('echo $PATH;2>&1',$op,$ret_val);
        $paths=explode(':',$output);

        foreach($paths as $path){
            if (file_exists($path.'/asterisk'))
                return $path.'/asterisk';
        }

        return null;
    }

    private function getAsteriskPid()
    {
        return exec('pidof asterisk');
    }

    private function initProcStatsArray()
    {
        return array('success'=>false);
    }

	public function actionIndex()
	{
        Yii::app()->session['stat_1']=$this->initProcStatsArray();
        Yii::app()->session['stat_2']=$this->initProcStatsArray();

		$this->render('index',
            array(
                'asteriskExists'=>$this->isAstriskExists()
            )
        );
	}

    public  function getProcsStat()
    {
        exec('cat /proc/stat;2>&1',$statData,$ret_val);

        $contProc=0;
        $stats=array();
        $stats['success']=true;
        $stats['cpus']=0;
        $stats['stats']=array();
        foreach ($statData as $line) {
            if (substr($line,0,3)=='cpu'){
                try{
                    $values=explode(' ',$line);

                    if (is_string((substr($values[0],3)))){
                        $stat=array();
                        $stat['user']=$values[1];
                        $stat['nice']=$values[2];
                        $stat['system']=$values[3];
                        $stat['idle']=$values[4];
                        $contProc++;
                        array_push($stats['stats'],$stat);
                    }
                }catch (Exception $e){
                    $stats['success']=false;
                }
            }
        }

        $stats['cpus']=$contProc;

        return $stats;
    }

    private function calcProcsLoadAvr()
    {
        $stats=$this->getProcsStat();

        $statCur= Yii::app()->session['stat_cur'];

        Yii::app()->session['stat_1']=Yii::app()->session['stat_2'];
        Yii::app()->session['stat_2']=$stats;

        $stat1=Yii::app()->session['stat_1'];
        $stat2=Yii::app()->session['stat_2'];

        $loadAvr=array();
        if (($stat1['success']==true)&& ($stat2['success']==true)){
            for ($i=0;$i<$stat1['cpus'];$i++){
                $s1=$stat1['stats'][$i];
                $s2=$stat2['stats'][$i];

                try {
                    $userd=$s2['user']-$s1['user'];
                    $niced=$s2['nice']-$s1['nice'];
                    $systemd=$s2['system']-$s1['system'];
                    $idled=$s2['idle']-$s1['idle'];

                    $devisor=$userd + $niced + $systemd + $idled;
                    if ($devisor!=0)
                        $load=100 * ($userd + $niced + $systemd)/$devisor;
                    else
                        $load=0;
                }catch (Exception $e){
                    $load=0;
                }

                array_push($loadAvr,round($load,2));
            }
        }

        return $loadAvr;
    }

    private function getProcsLoadAvr()
    {
        $loadAvr=$this->calcProcsLoadAvr();

        $count=count($loadAvr);

        if ($count==0)
            return null;

        $stats=array('cpus'=>$count,'loadavr'=>$loadAvr);

        return $stats;
    }

	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	public function actionLogin()
	{
		$model=new LoginForm;

		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		$this->render('login',array('model'=>$model));
	}

	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}

    private function getSystemMemInfo()
    {
        $data = explode("\n", file_get_contents("/proc/meminfo"));
        $meminfo = array();
        foreach ($data as $line) {
            if (trim($line)!=''){
                list($key, $val) = explode(":", $line);
                $meminfo[strtolower($key)] = str_replace('kB','',trim($val));
            }

        }
        return $meminfo;
    }

    private function getProcStatus($pid)
    {
        //$data = explode("\n", file_get_contents("/proc/26281/status"));
        exec('cat /proc/'.$pid.'/status;2>&1',$data,$ret_val);
        $status = array();
        foreach ($data as $line) {
            list($key, $val) = explode(":", $line);
            $status[strtolower($key)] = str_replace('kB','',trim($val));
        }
        return $status;
    }

    public function actionGetServerState()
    {
        header('Content-type: application/json');

        $meminfo=$this->getSystemMemInfo();

        try {
            $diskfree=round(disk_free_space('/')/(1024*1024*1024),2);
            $disktotal=round(disk_total_space('/')/(1024*1024*1024),2);
            $diskusage=$disktotal-$diskfree;
        }catch (Exception $e){
            $diskfree=0;
            $disktotal=0;
            $diskusage=0;
        }

        $serverState=array(
            'sizemem'=>'MB',
            'memtotal'=>floor($meminfo['memtotal']/1024),
            'memfree'=>floor($meminfo['memfree']/1024),
            'memusage'=>floor(($meminfo['memtotal']-$meminfo['memfree'])/1024),
            'sizeswap'=>'MB',
            'swaptotal'=>floor(($meminfo['swaptotal'])/1024),
            'swapfree'=>floor(($meminfo['swapfree'])/1024),
            'swapusage'=>floor(($meminfo['swaptotal']-$meminfo['swapfree'])/1024),
            'sizedisk'=>'GB',
            'disktotal'=>$disktotal,
            'diskfree'=>$diskfree,
            'diskusage'=>$diskusage,
            'cpuinfo'=>$this->getProcsLoadAvr()
        );

        echo CJSON::encode($serverState);
    }

    public function actionGetAsteriskState()
    {
        header('Content-type: application/json');

        $status=exec('/etc/init.d/asterisk status');
        $status=trim(str_replace('* status:','',$status));
        $pid=trim($this->getAsteriskPid());

        if (is_numeric($pid)){
            $procstatus=$this->getProcStatus($pid);
            $vmhwm=number_format($procstatus['vmhwm']/1024,2,'.',' ').' MB';
            $vmhwmraw=intval($procstatus['vmhwm']);
        }else{
            $vmhwm=0;
            $vmhwmraw=0;
            $pid=0;
        }

        echo CJSON::encode(array(
            'status' => $status,
            'pid' => $pid,
            'vmhwm' => $vmhwm,
            'vmhwmraw' => $vmhwmraw
        ));
    }

    public function actionDialplanReload($action)
    {
        $asteriskPath=$this->getAsteriskPath();
        if (!$asteriskPath)
            return;

        switch($action){
            case 'dr':
                $command='sudo '.$asteriskPath.' -x "dialplan reload"';
                break;
            case 'sr':
                $command='sudo '.$asteriskPath.' -x "sip reload"';
                break;
            case 'stop':
                $command='sudo '.$this->initScript.' stop;2>&1';
                break;
            case 'start':
                $command='sudo '.$this->initScript.' start > /dev/null 2>&1 &';
                break;
            case "restart":
                $command='sudo '.$this->initScript.' restart > /dev/null 2>&1 &';
                break;
            default:
                break;
        }

        $result=exec($command,$statData);
        for($i=0;$i<count($statData);$i++){
            echo $statData[$i].'<br>';
        }
    }

    public function actionIniFile()
    {
        $confFile=new ConfFile('chan_dahdi.conf');
        $confFile->addSection('dd');
    }

    public function actionCdr()
    {
        header('Content-Type: text/html; charset=utf-8');

        $dataProvider=new CActiveDataProvider('Cdr',array(
            'pagination'=>array(
                'pageSize'=>20
            )
        ));

        $this->setPageTitle('CDR');

        $this->render('cdr',array(
            'cdrs'=>$dataProvider
        ));
    }

}

protected/views/layouts/column0.php
<?php header('Content-Type: text/html; charset=utf-8'); ?>
<?php echo $content; ?>

protected/views/layouts/column1.php
<?php $this->beginContent('//layouts/main'); ?>
    <div class="container">
        <div class="col-12 col-lg-12">
                <?php echo $content; ?>
        </div>
    </div>
<?php $this->endContent(); ?>

protected/views/layouts/json.php
<?php header('Content-Type: application/json; charset=utf-8'); ?>
<?php echo $content; ?>

protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="language" content="ru" />
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css" media="screen" />
        <link rel="stylesheet" type="text/css" href="/css/bootstrap-theme.min.css" media="screen" />

        <link href="/images/login.png" rel="icon" type="image/x-icon">
        <title><?php echo CHtml::encode($this->pageTitle); ?></title>
    </head>

    <body>
        <?php
            $controller=Yii::app()->controller->id;
            $action=Yii::app()->controller->action->id;
        ?>
        <nav class="navbar-inverse navbar-fixed-top navbar" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <a class="navbar-brand" href="<?=$this->createUrl('/site')?>">
                        <!--<img style="margin-right: 3px" width="13px" alt src="/images/login.png">-->
                        <?php echo CHtml::encode(Yii::app()->name); ?>
                    </a>
                </div>
                <div class="collapse navbar-collapse" >
                    <ul class="navbar-nav navbar-right nav">
                        <li <?=(($controller=='site')&&($action=='index'))?'class="active"':'' ?> >
                            <a href="<?=$this->createUrl('/site')?>" >Главная</a>
                        </li>
                        <?php if (Yii::app()->user->isGuest) { ?>
                            <li <?=(($controller=='site')&&($action=='login'))?'class="active"':'' ?>>
                                <a href="<?=$this->createUrl('/site/login')?>">Вход</a>
                            </li>
                        <?php } else {?>
                            <li <?=(($controller=='extensions')&&($action=='index'))?'class="active"':'' ?>>
                                <a href="<?=$this->createUrl('/extensions')?>">План звонков</a>
                            </li>
                            <li class="<?=($controller=='conf')?'active':''?> dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Конфигурация<b class="caret" ></b></a>
                                <ul class="dropdown-menu">
                                    <li >
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::ASTERISK))?>">asterisk.conf</a>
                                    </li>
                                    <li>
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::CHAN_DAHDY))?>" >chan_dahdi.conf</a>
                                    </li>
                                    <li >
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::EXTCONFIG))?>">extconfig.conf</a>
                                    </li>
                                    <li >
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::FEATURES))?>">features.conf</a>
                                    </li>
                                    <li >
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::MODULES))?>">modules.conf</a>
                                    </li>
                                    <li >
                                        <a href="<?=$this->createUrl('/conf/index',array('c'=>AsteriskConfigs::SIP))?>">sip.conf</a>
                                    </li>
                                </ul>
                            </li>
                            <li <?=(($controller=='sips')&&($action=='index'))?'class="active"':'' ?> >
                                <a href="<?=$this->createUrl('/sips')?>">SIP</a>
                            </li>
                            <li <?=(($controller=='site')&&($action=='cdr'))?'class="active"':'' ?> >
                                <a href="<?=$this->createUrl('/site/cdr')?>">CDR</a>
                            </li>
                            <li <?=(($controller=='site')&&($action=='logout'))?'class="active"':'' ?> >
                                <a href="<?=$this->createUrl('/site/logout')?>">Выход(<?=Yii::app()->user->name?>)</a>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container" id="page">
            <div class="row" style="height: 60px;"></div>
            <div class="row">
                <?php echo $content; ?>
            </div>
            <div class="row" style="height: 60px;">
            <div class="navbar navbar-fixed-bottom navbar-inverse">
                <div class="container">
                    <div class="collapse navbar-collapse" style="text-align: center">
                        <p class="navbar-text" style="width: 100%">
                            Copyright &copy; <?php echo date('Y'); ?> ОАО Гамма.
                            <br/>
                            <?php echo Yii::powered(); ?>
                            /<a href="http://getbootstrap.com">Bootstrap</a>
                            /<a href="http://knockoutjs.com">knockoutjs</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <!--[if lt IE 8]>
            <script type="text/javascript" src="/js/css3-mediaqueries.js" />
        <![endif]-->

        <?php Yii::app()->getClientScript()->registerCoreScript('jquery'); ?>
        <script src="/js/bootstrap.min.js" ></script>
        <script src="/js/knockout.js" ></script>

        <!--Flash message -- begin-->
        <div id="flash-message" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Сообщение</h4>
                    </div>
                    <div class="modal-body" id="flash-message-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">ОК</button>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $("#flash-message").modal({show:false});

            <?php foreach(Yii::app()->user->getFlashes() as $key => $message) { ?>
                $("#flash-message-body").append(
                    '<div class="alert alert-<?=$key?>"><?=CHtml::encode($message)?>'
                );
                $("#flash-message").modal('show')
            <?php } ?>
        </script>
        <!--Flash message -- end-->
    </body>
</html>

protected/views/layouts/print.php
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <body>
        <?php echo $content; ?>
    </body>
<html>